const fs = require('fs');
const path = require('path');

function walkDir(dir, callback) {
    fs.readdirSync(dir).forEach(f => {
        let dirPath = path.join(dir, f);
        let isDirectory = fs.statSync(dirPath).isDirectory();
        isDirectory ? walkDir(dirPath, callback) : callback(path.join(dir, f));
    });
}
let c = 0;
walkDir('./client/src', function(filePath) {
    if (filePath.endsWith('.jsx') || filePath.endsWith('.js')) {
        let content = fs.readFileSync(filePath, 'utf8');
        let originalContent = content;

        // Problem 1: User's manual edit: `` {import...}  to `${import...}
        content = content.replace(/``\s*\{import\.meta\.env\.VITE_API_BASE_URL \|\| 'http:\/\/localhost:5134'\}/g, "`${import.meta.env.VITE_API_BASE_URL || 'http://localhost:5134'}");
        
        // Problem 2: Double backticks generated by powershell: ``${import...} to `${import...}
        content = content.replace(/``\$\{import\.meta\.env\.VITE_API_BASE_URL \|\| 'http:\/\/localhost:5134'\}/g, "`${import.meta.env.VITE_API_BASE_URL || 'http://localhost:5134'}");

        // Problem 3: Fix trailing broken templates...
        // Example: localhost:5134'}`/path -> localhost:5134'}/path
        content = content.replace(/localhost:5134'\}`\//g, "localhost:5134'}/");

        // Example: localhost:5134'}`${ -> localhost:5134'}${
        content = content.replace(/localhost:5134'\}`\$\{/g, "localhost:5134'}$\{");
        
        // General: If any string ends with '}` and has a `/` right after
        content = content.replace(/VITE_API_BASE_URL \|\| 'http:\/\/localhost:5134'\}`([^\S\r\n]*)[/`]/g, "VITE_API_BASE_URL || 'http://localhost:5134'}$1/");

        if(content !== originalContent) {
            fs.writeFileSync(filePath, content, 'utf8');
            c++;
            console.log('Fixed:', filePath);
        }
    }
});
console.log('Total fixed files: ' + c);
